dist: xenial
language: python
os:
  - linux
cache:
  pip: true
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install codecov
  - pip install .[dev]
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - flake8 .
  - py.test --cov=mesa tests/ --cov-report=xml
  - black --check --exclude=mesa/cookiecutter-mesa/* .
  # - ./tests/test_end_to_end_viz.sh  # needs to be investigated on why this took forever
after_success:
  - codecov
