language: python
os:
  - linux
python:
  - "3.4"
install:
  - apt-get install libblas-dev liblapack-dev
  - pip install -r requirements.txt
script:
  # ignore:
  # * E501 - line length limit
  # * E123 - indentation on data structures
  - flake8 . --ignore=F403,E501,E123 --exclude=docs/

after_success:
  - coveralls
